---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running
  service:
    name: nginx
    enabled: yes
    state: started

- name: Configure default site
  template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
