---
- name: Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql
    keyserver: keyserver.ubuntu.com
    key: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Install PostgreSQL 12
  apt:
    name: postgresql-12
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    enabled: yes
    state: started
