---
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Elastic GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: elastic-7.x

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Install Kibana
  apt:
    name: kibana
    state: present

- name: Ensure services are running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - elasticsearch
    - logstash
    - kibana
