---
- name: Add Zabbix repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.0/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    filename: zabbix
    key: https://repo.zabbix.com/zabbix-official-repo.key

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2 zabbix-agent2-plugin-*
    state: present
    update_cache: yes

- name: Configure Zabbix Agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
  notify: restart zabbix-agent2

- name: Ensure Zabbix Agent 2 is running
  service:
    name: zabbix-agent2
    enabled: yes
    state: started

