---
- name: Install BIND9
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: Configure BIND options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Configure BIND local zones
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9

- name: Ensure BIND is running
  service:
    name: bind9
    enabled: yes
    state: started
